CREATE DATABASE IF NOT EXISTS musicmart;
USE musicmart;
CREATE TABLE IF NOT EXISTS products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  image       VARCHAR(255),
  price       DECIMAL(12,2) DEFAULT 0,
  brand       VARCHAR(255),
  stock       INT DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
